package dockerize

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// DockerfileGenerator generates Dockerfiles based on project type.
type DockerfileGenerator struct {
	ProjectDir string
}

type projectInfo struct {
	Type       string
	EntryPoint string
	BinaryName string
}

// DetectProjectType detects the primary type of project in the given directory.
func DetectProjectType(dir string) string {
	return detectProject(dir).Type
}

// GenerateDockerfile creates a Dockerfile based on project type.
func GenerateDockerfile(dir string) (string, error) {
	project := detectProject(dir)

	switch project.Type {
	case "python":
		return generatePythonDockerfile(dir, project), nil
	case "node":
		return generateNodeDockerfile(dir, project), nil
	case "go":
		return generateGoDockerfile(dir, project), nil
	case "rust":
		return generateRustDockerfile(dir, project), nil
	default:
		return "", fmt.Errorf("unsupported project type or no recognized project found in %s", dir)
	}
}

func detectProject(dir string) projectInfo {
	if fileExists(filepath.Join(dir, "requirements.txt")) ||
		fileExists(filepath.Join(dir, "pyproject.toml")) ||
		fileExists(filepath.Join(dir, "setup.py")) {
		return projectInfo{Type: "python", EntryPoint: detectPythonEntrypoint(dir)}
	}

	if fileExists(filepath.Join(dir, "package.json")) {
		return projectInfo{Type: "node", EntryPoint: detectNodeEntrypoint(dir)}
	}

	if fileExists(filepath.Join(dir, "go.mod")) {
		binary, target := detectGoBuildTarget(dir)
		return projectInfo{Type: "go", EntryPoint: target, BinaryName: binary}
	}

	if fileExists(filepath.Join(dir, "Cargo.toml")) {
		return projectInfo{Type: "rust", BinaryName: detectRustBinaryName(dir), EntryPoint: detectRustEntrypoint(dir)}
	}

	return projectInfo{Type: "unknown"}
}

func generatePythonDockerfile(dir string, project projectInfo) string {
	hasRequirements := fileExists(filepath.Join(dir, "requirements.txt"))
	hasPyproject := fileExists(filepath.Join(dir, "pyproject.toml"))
	hasSetup := fileExists(filepath.Join(dir, "setup.py")) || fileExists(filepath.Join(dir, "setup.cfg"))

	var dockerfile strings.Builder
	dockerfile.WriteString("# Python Dockerfile generated by envdoctor\n")
	writeDockerignoreSuggestion(&dockerfile)
	dockerfile.WriteString("FROM python:3.12-slim\n\n")
	dockerfile.WriteString("ENV PYTHONDONTWRITEBYTECODE=1\n")
	dockerfile.WriteString("ENV PYTHONUNBUFFERED=1\n\n")
	dockerfile.WriteString("WORKDIR /app\n\n")
	dockerfile.WriteString("RUN useradd --create-home --shell /usr/sbin/nologin appuser\n\n")

	if hasRequirements {
		dockerfile.WriteString("COPY requirements.txt ./\n")
		dockerfile.WriteString("RUN pip install --no-cache-dir -r requirements.txt\n\n")
	}
	if hasPyproject || hasSetup {
		copyFiles := existingFiles(dir, "pyproject.toml", "setup.py", "setup.cfg")
		if len(copyFiles) > 0 {
			dockerfile.WriteString("COPY ")
			dockerfile.WriteString(strings.Join(copyFiles, " "))
			dockerfile.WriteString(" ./\n")
			dockerfile.WriteString("RUN pip install --no-cache-dir -e .\n\n")
		}
	}

	dockerfile.WriteString("COPY . .\n")
	dockerfile.WriteString("RUN chown -R appuser:appuser /app\n")
	dockerfile.WriteString("USER appuser\n\n")

	if project.EntryPoint != "" {
		dockerfile.WriteString(fmt.Sprintf("CMD [\"python\", \"%s\"]\n", project.EntryPoint))
	} else {
		dockerfile.WriteString("# No Python entrypoint detected. Update CMD for your application.\n")
		dockerfile.WriteString("# CMD [\"python\", \"main.py\"]\n")
	}

	return dockerfile.String()
}

func generateNodeDockerfile(dir string, project projectInfo) string {
	hasLock := fileExists(filepath.Join(dir, "package-lock.json"))

	var dockerfile strings.Builder
	dockerfile.WriteString("# Node.js Dockerfile generated by envdoctor\n")
	writeDockerignoreSuggestion(&dockerfile)
	dockerfile.WriteString("FROM node:20-slim\n\n")
	dockerfile.WriteString("WORKDIR /app\n\n")
	if hasLock {
		dockerfile.WriteString("COPY package.json package-lock.json ./\n")
		dockerfile.WriteString("RUN npm ci --omit=dev\n\n")
	} else {
		dockerfile.WriteString("COPY package*.json ./\n")
		dockerfile.WriteString("RUN npm install --omit=dev\n\n")
	}
	dockerfile.WriteString("COPY . .\n")
	dockerfile.WriteString("RUN chown -R node:node /app\n")
	dockerfile.WriteString("USER node\n\n")

	if project.EntryPoint == "npm start" {
		dockerfile.WriteString("CMD [\"npm\", \"start\"]\n")
	} else if project.EntryPoint != "" {
		dockerfile.WriteString(fmt.Sprintf("CMD [\"node\", \"%s\"]\n", project.EntryPoint))
	} else {
		dockerfile.WriteString("# No Node.js entrypoint detected. Update CMD for your application.\n")
		dockerfile.WriteString("# CMD [\"npm\", \"start\"]\n")
	}

	return dockerfile.String()
}

func generateGoDockerfile(dir string, project projectInfo) string {
	binaryName := project.BinaryName
	if binaryName == "" {
		binaryName = "app"
	}
	buildTarget := project.EntryPoint

	var dockerfile strings.Builder
	dockerfile.WriteString("# Go Dockerfile generated by envdoctor (multi-stage build)\n")
	writeDockerignoreSuggestion(&dockerfile)
	dockerfile.WriteString("FROM golang:1.22-alpine AS builder\n\n")
	dockerfile.WriteString("WORKDIR /app\n\n")
	dockerfile.WriteString("COPY go.mod")
	if fileExists(filepath.Join(dir, "go.sum")) {
		dockerfile.WriteString(" go.sum")
	}
	dockerfile.WriteString(" ./\n")
	dockerfile.WriteString("RUN go mod download\n\n")
	dockerfile.WriteString("COPY . .\n")
	if buildTarget != "" {
		dockerfile.WriteString(fmt.Sprintf("RUN CGO_ENABLED=0 GOOS=linux go build -o /out/%s %s\n\n", binaryName, buildTarget))
	} else {
		dockerfile.WriteString("# No Go main package detected. Update the build target for your application.\n")
		dockerfile.WriteString(fmt.Sprintf("# RUN CGO_ENABLED=0 GOOS=linux go build -o /out/%s ./cmd/%s\n\n", binaryName, binaryName))
	}
	dockerfile.WriteString("FROM alpine:3.20\n\n")
	dockerfile.WriteString("WORKDIR /app\n")
	dockerfile.WriteString("RUN adduser -D -H appuser\n")
	if buildTarget != "" {
		dockerfile.WriteString(fmt.Sprintf("COPY --from=builder /out/%s ./%s\n", binaryName, binaryName))
	} else {
		dockerfile.WriteString(fmt.Sprintf("# COPY --from=builder /out/%s ./%s\n", binaryName, binaryName))
	}
	dockerfile.WriteString("USER appuser\n\n")
	if buildTarget != "" {
		dockerfile.WriteString(fmt.Sprintf("CMD [\"./%s\"]\n", binaryName))
	} else {
		dockerfile.WriteString(fmt.Sprintf("# CMD [\"./%s\"]\n", binaryName))
	}

	return dockerfile.String()
}

func generateRustDockerfile(dir string, project projectInfo) string {
	binaryName := project.BinaryName
	if binaryName == "" {
		binaryName = "app"
	}

	var dockerfile strings.Builder
	dockerfile.WriteString("# Rust Dockerfile generated by envdoctor (multi-stage build)\n")
	writeDockerignoreSuggestion(&dockerfile)
	dockerfile.WriteString("FROM rust:1.82-slim AS builder\n\n")
	dockerfile.WriteString("WORKDIR /app\n\n")
	dockerfile.WriteString("COPY Cargo.toml")
	if fileExists(filepath.Join(dir, "Cargo.lock")) {
		dockerfile.WriteString(" Cargo.lock")
	}
	dockerfile.WriteString(" ./\n")
	if project.EntryPoint != "" {
		dockerfile.WriteString("RUN mkdir src && echo 'fn main() {}' > src/main.rs\n")
		dockerfile.WriteString("RUN cargo build --release && rm -rf src\n\n")
	}
	dockerfile.WriteString("COPY . .\n")
	dockerfile.WriteString("RUN cargo build --release\n\n")
	dockerfile.WriteString("FROM debian:bookworm-slim\n\n")
	dockerfile.WriteString("WORKDIR /app\n")
	dockerfile.WriteString("RUN useradd --create-home --shell /usr/sbin/nologin appuser\n")
	if project.EntryPoint != "" {
		dockerfile.WriteString(fmt.Sprintf("COPY --from=builder /app/target/release/%s ./%s\n", binaryName, binaryName))
	} else {
		dockerfile.WriteString(fmt.Sprintf("# COPY --from=builder /app/target/release/%s ./%s\n", binaryName, binaryName))
	}
	dockerfile.WriteString("USER appuser\n\n")
	if project.EntryPoint != "" {
		dockerfile.WriteString(fmt.Sprintf("CMD [\"./%s\"]\n", binaryName))
	} else {
		dockerfile.WriteString("# No Rust binary entrypoint detected. Update COPY and CMD for your target binary.\n")
		dockerfile.WriteString(fmt.Sprintf("# CMD [\"./%s\"]\n", binaryName))
	}

	return dockerfile.String()
}

func detectPythonEntrypoint(dir string) string {
	candidates := []string{"app.py", "main.py", filepath.Join("src", "main.py"), filepath.Join("src", "app.py")}
	for _, candidate := range candidates {
		if fileExists(filepath.Join(dir, candidate)) {
			return filepath.ToSlash(candidate)
		}
	}
	return ""
}

func detectNodeEntrypoint(dir string) string {
	data, err := os.ReadFile(filepath.Join(dir, "package.json"))
	if err == nil {
		var pkg struct {
			Main    string            `json:"main"`
			Scripts map[string]string `json:"scripts"`
		}
		if json.Unmarshal(data, &pkg) == nil {
			if pkg.Scripts != nil && pkg.Scripts["start"] != "" {
				return "npm start"
			}
			if pkg.Main != "" {
				return pkg.Main
			}
		}
	}

	for _, candidate := range []string{"server.js", "index.js", filepath.Join("src", "index.js")} {
		if fileExists(filepath.Join(dir, candidate)) {
			return filepath.ToSlash(candidate)
		}
	}
	return ""
}

func detectGoBuildTarget(dir string) (string, string) {
	if mainGoContainsPackageMain(filepath.Join(dir, "main.go")) {
		return safeName(filepath.Base(dir)), "."
	}

	cmdDir := filepath.Join(dir, "cmd")
	entries, err := os.ReadDir(cmdDir)
	if err == nil {
		for _, entry := range entries {
			if !entry.IsDir() {
				continue
			}
			mainPath := filepath.Join(cmdDir, entry.Name(), "main.go")
			if mainGoContainsPackageMain(mainPath) {
				return safeName(entry.Name()), "./cmd/" + entry.Name()
			}
		}
	}

	return safeName(filepath.Base(dir)), ""
}

func mainGoContainsPackageMain(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), "package main")
}

func detectRustEntrypoint(dir string) string {
	if fileExists(filepath.Join(dir, "src", "main.rs")) {
		return filepath.ToSlash(filepath.Join("src", "main.rs"))
	}
	return ""
}

func detectRustBinaryName(dir string) string {
	data, err := os.ReadFile(filepath.Join(dir, "Cargo.toml"))
	if err != nil {
		return safeName(filepath.Base(dir))
	}

	re := regexp.MustCompile(`(?m)^\s*name\s*=\s*"([^"]+)"`)
	match := re.FindStringSubmatch(string(data))
	if len(match) == 2 {
		return safeName(match[1])
	}
	return safeName(filepath.Base(dir))
}

// SaveDockerfile saves the generated Dockerfile to the project directory.
func SaveDockerfile(content, dir string) error {
	return SaveDockerfileTo(content, filepath.Join(dir, "Dockerfile"), false)
}

// SaveDockerfileTo saves a Dockerfile and refuses to overwrite unless force is true.
func SaveDockerfileTo(content, path string, force bool) error {
	if !force && fileExists(path) {
		return fmt.Errorf("%s already exists; use --force to overwrite", path)
	}
	return os.WriteFile(path, []byte(content), 0644)
}

func writeDockerignoreSuggestion(builder *strings.Builder) {
	builder.WriteString("# Recommended .dockerignore entries: .git, node_modules, target, dist, __pycache__, .venv\n")
}

func existingFiles(dir string, names ...string) []string {
	var files []string
	for _, name := range names {
		if fileExists(filepath.Join(dir, name)) {
			files = append(files, name)
		}
	}
	return files
}

func safeName(name string) string {
	name = strings.TrimSpace(strings.ToLower(name))
	if name == "" || name == "." || name == "/" {
		return "app"
	}
	re := regexp.MustCompile(`[^a-z0-9_.-]+`)
	name = re.ReplaceAllString(name, "-")
	name = strings.Trim(name, "-_.")
	if name == "" {
		return "app"
	}
	return name
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}
