package dockerize

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// DockerfileGenerator generates Dockerfiles based on project type
type DockerfileGenerator struct {
	ProjectDir string
}

// DetectProjectType detects the type of project in the given directory
func DetectProjectType(dir string) string {
	// Python projects
	if _, err := os.Stat(filepath.Join(dir, "requirements.txt")); err == nil {
		return "python"
	}
	if _, err := os.Stat(filepath.Join(dir, "pyproject.toml")); err == nil {
		return "python"
	}
	if _, err := os.Stat(filepath.Join(dir, "setup.py")); err == nil {
		return "python"
	}

	// Node.js projects
	if _, err := os.Stat(filepath.Join(dir, "package.json")); err == nil {
		return "node"
	}

	// Go projects
	if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
		return "go"
	}

	// Rust projects
	if _, err := os.Stat(filepath.Join(dir, "Cargo.toml")); err == nil {
		return "rust"
	}

	return "unknown"
}

// GenerateDockerfile creates a Dockerfile based on project type
func GenerateDockerfile(dir string) (string, error) {
	projectType := DetectProjectType(dir)
	
	switch projectType {
	case "python":
		return generatePythonDockerfile(dir), nil
	case "node":
		return generateNodeDockerfile(dir), nil
	case "go":
		return generateGoDockerfile(dir), nil
	case "rust":
		return generateRustDockerfile(dir), nil
	default:
		return "", fmt.Errorf("unsupported project type or no recognized project found in %s", dir)
	}
}

func generatePythonDockerfile(dir string) string {
	// Check for specific Python files to determine base image
	hasPip := false
	if _, err := os.Stat(filepath.Join(dir, "requirements.txt")); err == nil {
		hasPip = true
	}

	hasPyproject := false
	if _, err := os.Stat(filepath.Join(dir, "pyproject.toml")); err == nil {
		hasPyproject = true
	}

	var dockerfile strings.Builder
	dockerfile.WriteString("# Python Dockerfile generated by envdoctor\n")
	dockerfile.WriteString("FROM python:3.11-slim\n\n")
	dockerfile.WriteString("WORKDIR /app\n\n")
	dockerfile.WriteString("COPY . .\n\n")

	if hasPip {
		dockerfile.WriteString("RUN pip install --no-cache-dir -r requirements.txt\n\n")
	}

	if hasPyproject {
		dockerfile.WriteString("RUN pip install --no-cache-dir -e .\n\n")
	}

	// Try to detect entry point
	if _, err := os.Stat(filepath.Join(dir, "app.py")); err == nil {
		dockerfile.WriteString("CMD [\"python\", \"app.py\"]\n")
	} else if _, err := os.Stat(filepath.Join(dir, "main.py")); err == nil {
		dockerfile.WriteString("CMD [\"python\", \"main.py\"]\n")
	} else {
		dockerfile.WriteString("# Please specify the entry point for your application\n")
		dockerfile.WriteString("# CMD [\"python\", \"your_app.py\"]\n")
	}

	return dockerfile.String()
}

func generateNodeDockerfile(dir string) string {
	var dockerfile strings.Builder
	dockerfile.WriteString("# Node.js Dockerfile generated by envdoctor\n")
	dockerfile.WriteString("FROM node:18-slim\n\n")
	dockerfile.WriteString("WORKDIR /app\n\n")
	dockerfile.WriteString("COPY package*.json ./\n")
	dockerfile.WriteString("RUN npm install\n\n")
	dockerfile.WriteString("COPY . .\n\n")

	// Check for common entry points
	if _, err := os.Stat(filepath.Join(dir, "server.js")); err == nil {
		dockerfile.WriteString("CMD [\"node\", \"server.js\"]\n")
	} else if _, err := os.Stat(filepath.Join(dir, "index.js")); err == nil {
		dockerfile.WriteString("CMD [\"node\", \"index.js\"]\n")
	} else {
		dockerfile.WriteString("# Please specify the entry point for your application\n")
		dockerfile.WriteString("# CMD [\"node\", \"your_app.js\"]\n")
	}

	return dockerfile.String()
}

func generateGoDockerfile(dir string) string {
	var dockerfile strings.Builder
	dockerfile.WriteString("# Go Dockerfile generated by envdoctor (multi-stage build)\n\n")
	
	// Build stage
	dockerfile.WriteString("# Build stage\n")
	dockerfile.WriteString("FROM golang:1.21-alpine AS builder\n\n")
	dockerfile.WriteString("WORKDIR /app\n\n")
	dockerfile.WriteString("COPY go.mod go.sum ./\n")
	dockerfile.WriteString("RUN go mod download\n\n")
	dockerfile.WriteString("COPY . .\n")
	dockerfile.WriteString("RUN CGO_ENABLED=0 GOOS=linux go build -o main .\n\n")
	
	// Final stage
	dockerfile.WriteString("# Final stage\n")
	dockerfile.WriteString("FROM alpine:latest\n\n")
	dockerfile.WriteString("WORKDIR /root/\n\n")
	dockerfile.WriteString("COPY --from=builder /app/main .\n\n")
	dockerfile.WriteString("CMD [\"./main\"]\n")

	return dockerfile.String()
}

func generateRustDockerfile(dir string) string {
	var dockerfile strings.Builder
	dockerfile.WriteString("# Rust Dockerfile generated by envdoctor (multi-stage build)\n\n")
	
	// Build stage
	dockerfile.WriteString("# Build stage\n")
	dockerfile.WriteString("FROM rust:1.72-slim AS builder\n\n")
	dockerfile.WriteString("WORKDIR /app\n\n")
	dockerfile.WriteString("COPY Cargo.toml Cargo.lock ./\n")
	dockerfile.WriteString("RUN mkdir src && echo 'fn main() {}' > src/main.rs\n")
	dockerfile.WriteString("RUN cargo build --release && rm -rf src\n\n")
	dockerfile.WriteString("COPY . .\n")
	dockerfile.WriteString("RUN cargo build --release\n\n")
	
	// Final stage
	dockerfile.WriteString("# Final stage\n")
	dockerfile.WriteString("FROM debian:bookworm-slim\n\n")
	dockerfile.WriteString("WORKDIR /app\n\n")
	dockerfile.WriteString("COPY --from=builder /app/target/release/* ./\n\n")
	dockerfile.WriteString("# Please update the CMD to point to your binary\n")
	dockerfile.WriteString("CMD [\"./your_binary\"]\n")

	return dockerfile.String()
}

// SaveDockerfile saves the generated Dockerfile to disk
func SaveDockerfile(content, dir string) error {
	path := filepath.Join(dir, "Dockerfile")
	return os.WriteFile(path, []byte(content), 0644)
}
